// admin/web/src/pages/Overview.tsx
/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { useCallback, useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowRight, Plus, Trash } from '@phosphor-icons/react'
import { createResource, deleteResource, getBaseInfo, getResourceList, setBaseInfo } from '../api'
import { Resource } from '../types'
import { Button, EmptyState, ErrorState, formatDuration, Loading, Panel, Tag } from '../components/common'
import { ConfirmModal, Modal } from '../components/Modal'
import { YamlEditor } from '../components/YamlEditor'
import { useToast } from '../components/Toast'

const RESOURCE_TEMPLATE = `type: restful
path: /api/v1/example
timeout: 1s
description: ''
filters: []
methods: []
`

export function OverviewPage() {
  const navigate = useNavigate()
  const toast = useToast()

  const [baseYaml, setBaseYaml] = useState('')
  const [baseLoading, setBaseLoading] = useState(true)
  const [baseError, setBaseError] = useState('')
  const [baseSaving, setBaseSaving] = useState(false)

  const [resources, setResources] = useState<Resource[]>([])
  const [listLoading, setListLoading] = useState(true)
  const [listError, setListError] = useState('')

  const [createOpen, setCreateOpen] = useState(false)
  const [createYaml, setCreateYaml] = useState(RESOURCE_TEMPLATE)
  const [creating, setCreating] = useState(false)

  const [deleteTarget, setDeleteTarget] = useState<Resource | null>(null)
  const [deleting, setDeleting] = useState(false)

  const loadBase = useCallback(async () => {
    setBaseLoading(true)
    setBaseError('')
    try {
      setBaseYaml(await getBaseInfo())
    } catch (err) {
      // Key missing on a fresh etcd is normal; keep the editor writable so
      // the config can be created for the first time.
      setBaseYaml('')
      setBaseError(err instanceof Error ? err.message : '加载基础配置失败')
    } finally {
      setBaseLoading(false)
    }
  }, [])

  const loadResources = useCallback(async () => {
    setListLoading(true)
    setListError('')
    try {
      setResources(await getResourceList())
    } catch (err) {
      setListError(err instanceof Error ? err.message : '加载 Resource 列表失败')
    } finally {
      setListLoading(false)
    }
  }, [])

  useEffect(() => {
    void loadBase()
    void loadResources()
  }, [loadBase, loadResources])

  const handleSaveBase = async () => {
    setBaseSaving(true)
    try {
      await setBaseInfo(baseYaml)
      toast.success('基础配置已保存')
    } catch (err) {
      toast.error(err instanceof Error ? err.message : '保存失败')
    } finally {
      setBaseSaving(false)
    }
  }

  const handleCreate = async () => {
    setCreating(true)
    try {
      await createResource(createYaml)
      toast.success('Resource 已创建')
      setCreateOpen(false)
      setCreateYaml(RESOURCE_TEMPLATE)
      void loadResources()
    } catch (err) {
      toast.error(err instanceof Error ? err.message : '创建失败')
    } finally {
      setCreating(false)
    }
  }

  const handleDelete = async () => {
    if (!deleteTarget?.id) return
    setDeleting(true)
    try {
      await deleteResource(deleteTarget.id)
      toast.success(`Resource ${deleteTarget.id} 已删除`)
      setDeleteTarget(null)
      void loadResources()
    } catch (err) {
      toast.error(err instanceof Error ? err.message : '删除失败')
    } finally {
      setDeleting(false)
    }
  }

  return (
    <div className="mx-auto max-w-[1400px] space-y-4">
      <Panel
        title="基础网关配置"
        extra={
          <Button variant="primary" onClick={handleSaveBase} loading={baseSaving} disabled={baseLoading}>
            保存
          </Button>
        }
      >
        {baseLoading ? (
          <Loading />
        ) : (
          <>
            {baseError ? (
              <p className="mb-3 flex items-center justify-between gap-2 rounded-md bg-amber-50 px-3 py-2 text-xs text-amber-700">
                <span>未能读取现有配置（{baseError}）。可直接编辑并保存以创建。</span>
                <button type="button" className="shrink-0 font-medium underline hover:text-amber-800" onClick={() => void loadBase()}>
                  重试
                </button>
              </p>
            ) : null}
            <YamlEditor value={baseYaml} onChange={setBaseYaml} height={220} />
          </>
        )}
      </Panel>

      <Panel
        title="Resource 列表"
        extra={
          <div className="flex items-center gap-2">
            <Button onClick={() => void loadResources()}>刷新</Button>
            <Button variant="primary" onClick={() => setCreateOpen(true)}>
              <Plus size={15} />
              新增 Resource
            </Button>
          </div>
        }
        bodyClassName="p-0"
      >
        {listLoading ? (
          <Loading />
        ) : listError ? (
          <ErrorState text={listError} onRetry={loadResources} />
        ) : resources.length === 0 ? (
          <EmptyState
            text="暂无 Resource，点击右上角新增。"
            action={
              <Button variant="primary" onClick={() => setCreateOpen(true)}>
                <Plus size={15} />
                新增 Resource
              </Button>
            }
          />
        ) : (
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-slate-100 text-left text-xs text-slate-500">
                <th className="px-4 py-2.5 font-medium">ID</th>
                <th className="px-4 py-2.5 font-medium">类型</th>
                <th className="px-4 py-2.5 font-medium">路径</th>
                <th className="px-4 py-2.5 font-medium">超时</th>
                <th className="px-4 py-2.5 font-medium">描述</th>
                <th className="px-4 py-2.5 text-right font-medium">操作</th>
              </tr>
            </thead>
            <tbody>
              {resources.map((item) => (
                <tr key={item.id} className="border-b border-slate-50 last:border-0 hover:bg-slate-50/60">
                  <td className="px-4 py-2.5 font-mono text-xs text-slate-600">{item.id}</td>
                  <td className="px-4 py-2.5">
                    <Tag tone="blue">{item.type || '-'}</Tag>
                  </td>
                  <td className="max-w-64 truncate px-4 py-2.5 font-mono text-xs text-slate-700">{item.path}</td>
                  <td className="px-4 py-2.5 text-slate-600">{formatDuration(item.timeout)}</td>
                  <td className="max-w-52 truncate px-4 py-2.5 text-slate-500">{item.description || '-'}</td>
                  <td className="px-4 py-2.5">
                    <div className="flex items-center justify-end gap-1">
                      <Button variant="ghost" className="px-2" onClick={() => navigate(`/gateway/mapping/${item.id}`)}>
                        映射详情
                        <ArrowRight size={14} />
                      </Button>
                      <Button variant="ghost" className="px-2 text-rose-600 hover:bg-rose-50" onClick={() => setDeleteTarget(item)}>
                        <Trash size={15} />
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </Panel>

      <Modal
        open={createOpen}
        title="新增 Resource"
        width="lg"
        onClose={() => setCreateOpen(false)}
        footer={
          <>
            <Button onClick={() => setCreateOpen(false)}>取消</Button>
            <Button variant="primary" loading={creating} onClick={handleCreate}>
              创建
            </Button>
          </>
        }
      >
        <p className="mb-2 text-xs text-slate-500">以 YAML 描述 Resource，创建后可在列表中进入其方法映射详情。</p>
        <YamlEditor value={createYaml} onChange={setCreateYaml} height={320} />
      </Modal>

      <ConfirmModal
        open={deleteTarget !== null}
        title="删除 Resource"
        danger
        loading={deleting}
        confirmText="删除"
        message={
          <>
            确定删除 Resource <span className="font-mono text-slate-800">{deleteTarget?.path}</span>（ID {deleteTarget?.id}）吗？
            其下的 Method 映射会一并失效。
          </>
        }
        onConfirm={handleDelete}
        onClose={() => setDeleteTarget(null)}
      />
    </div>
  )
}

// admin/web/src/views/dashboard/manage/Overview.vue
<!--
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 -->
<template>
    <CustomLayout >
    <div class="custom-body">
      <div>
        <CommonTitle title="概览"></CommonTitle>
      </div>
      <!-- <div class="custom-tools">
        <div class="table-head">
          <div class="custom-tools__info">基础信息</div>
          <el-button type="primary" icon="el-icon-plus" size="mini"
                     @click="handleChange">修改</el-button>
        </div>
        
        <div class="custom-tools__content">
          <el-form :model="form"
                 :inline="true"
                 @submit.native.prevent=""
                 class="table-form bg-gray"
                 label-width="130px">
          <el-row>
            <div style="clear: 'both'; height: 100px;width: 100%;" id="containForm" ref="containForm"/>
          </el-row>
        </el-form>
        </div>
      </div> -->
      <div class="table-head">
        <div class="custom-tools__info">映射服务</div>
        <el-button type="primary" icon="el-icon-plus" size="mini"
                     @click="handleAdd">新增</el-button>
      </div>
      <div class="custom-panel">
        <el-table v-loading="loading"
                  size="normal"
                  :data="tableData"
                  :empty-text="emptText"
                  row-class-name="custom-table-tr--hover"
                  header-row-class-name="custom-table-header"
                  @selection-change="handleSelectionChange"
                  style="width: 100%">
          <el-table-column 
                           prop="id"
                           label="ID">
            
          </el-table-column>
          <el-table-column 
                           prop=""
                           label="映射服务">
            
          </el-table-column>
          <el-table-column prop="path"
                           label="路径">
          </el-table-column>
          <el-table-column 
                           prop="type"
                           label="类型">
          </el-table-column>
          <el-table-column
                           prop="description"
                           label="描述">
          </el-table-column>
          <el-table-column
                           label="操作">
            <template slot-scope="scope">

              <el-button type="text"
                         @click="handleLook(scope.row)">查看</el-button>
              <el-button type="text" class="dltbtn"
                         @click="deleteRow(scope.row)">删除</el-button>
            </template>
          </el-table-column>
        </el-table>

        <div class="custom-pagination"
             style="float:right">
          
          <div style="display: flex;">
            <div>
              总共<span>{{ pagination.total }}</span>条记录<i class="custom-pagination__interval"></i>每页显示
              <el-select v-model="pagination.pageSize"
                         placeholder="请选择"
                         style="width:70px;">
                <el-option v-for="item in pagination.pageSizes"
                           :key="item"
                           :label="item"
                           :value="item">
                </el-option>
              </el-select>
              条记录
            </div>
            <el-pagination :current-page.sync="pagination.pageIndex"
                           :page-size.sync="pagination.pageSize"
                           layout="prev, pager, next"
                           :total="pagination.total">
            </el-pagination>
          </div>
        </div>
      </div>
    </div>
    <el-dialog
                title="新增"
                :visible.sync="dialogVisible"
                width="640px"
                :before-close="handleClose">
            <div class="dialog_main">
                <div style="clear: 'both'; height: 300px;width: 100%;" id="container" ref="container"/>
            </div>
            <span slot="footer" class="dialog-footer">
                <el-button size="mini" @click="handleClose">取 消</el-button>
                <el-button type="primary"  size="mini" @click="makeSure">确 定</el-button>
            </span>
        </el-dialog>
  </CustomLayout>
</template>

<script>
import CommonTitle from '@/components/common/CommonTitle'
import CustomLayout from '@/components/common/CustomLayout.vue'
import * as monaco from 'monaco-editor/esm/vs/editor/editor.main.js'
import 'monaco-editor/esm/vs/basic-languages/javascript/javascript.contribution'
import { StandaloneCodeEditorServiceImpl } from 'monaco-editor/esm/vs/editor/standalone/browser/standaloneCodeServiceImpl.js'

export default {
  name: '',
  components:{
    CommonTitle,
    CustomLayout
  },
  data () {
    return {
      form:{

      },
      edit:false,
      dialogVisible:false,
      chooseRow:{
        timeout:'',
        description:'',
        type:'',
        path:''
      },
      pagination: { // 分页字段
        pageIndex: 1, // 当前页
        pageSize: 20, // 每页显示多少条
        total: 0, // 总条数
        pageSizes: [20, 50, 100]
      },
      tableData: [], // table列表数据
      loading: false,
      tableHeight: window.document.documentElement.clientHeight - 248, // table高度
      multipleSelection: [], // 多选时，已选项
      currentRow: {}, // 当前选中行
      areaDialogVisible: false, // 是否显示行政区划弹窗
      emptText: '暂无数据', // table数据为空的提示语
      isSizeInit: false, // 是否是页面初始化时设置的PageSize
      previewDialogVisible: false, // 是否显示行政区划弹窗
      currentTemplate: {},//当前选中的模板
      monacoEditor: null,
      monacoEditored: null,
      detailSource:null,
    }
  },
  mounted() {
    //获取基础信息
    this.init()
    //获取 Resource 列表
    this.getResourceList()
  },
  methods: {
    initMoacoEditor(language, value) {
      this.monacoEditor = monaco.editor.create(document.getElementById('container'), {
        value,
        language: 'yaml',
        codeLens: true,
        selectOnLineNumbers: true,
        roundedSelection: false,
        readOnly: false,
        lineNumbersMinChars: true,
        theme: 'vs-dark',
        wordWrapColumn: 120,
        folding: false,
        showFoldingControls: 'always',
        wordWrap: 'wordWrapColumn',
        cursorStyle: 'line',
        automaticLayout: true,
      });
    },
    initMoacoEditored(language, value) {
      this.monacoEditored = monaco.editor.create(document.getElementById('containForm'), {
        value,
        language: 'yaml',
        codeLens: true,
        selectOnLineNumbers: true,
        roundedSelection: false,
        readOnly: false,
        lineNumbersMinChars: true,
        theme: 'vs-dark',
        wordWrapColumn: 120,
        folding: false,
        showFoldingControls: 'always',
        wordWrap: 'wordWrapColumn',
        cursorStyle: 'line',
        automaticLayout: true,
      });
    },
    handleLook(row) {
      this.$router.push({
        path:'/Mapping',
        query:{
          queryId: row.id
        }
      })
    },
    handleClose() {
      this.dialogVisible = false
      this.monacoEditor.dispose();
    },
    //映射服务列表
    getResourceList() {
      this.$get('/config/api/resource/list')
        .then((res) => {
          if (res.code == 10001) {
             this.tableData = JSON.parse(res.data)
             this.pagination.total = this.tableData.length
          } else {
            
          }
        })
        .catch((err) => {
          console.log(err)
        })
    },
     //获取基础信息
    init() {  
      this.$get('/config/api/base')
        .then((res) => {
          if (res.code == 10001) {
            this.$nextTick(() =>[
              this.initMoacoEditored('yaml', res.data)
            ])
          } else {
            this.$nextTick(() =>[
              this.initMoacoEditored('yaml', '')
            ])
          }
        })
        .catch((err) => {
          console.log(err)
        })
    },
    handleSelectionChange(val) {
      this.multipleSelection = val
    },
    //修改用户信息
    handleChange() {
      let formData = new FormData();
      let data = this.monacoEditored.getValue()
      formData.append('content', data);
      this.$post('/config/api/base', formData)
        .then((res) => {
          if (res.code == 10001) {
            this.$message({
              type: 'success',
              message: '修改成功！',
            })
            this.monacoEditored.dispose()
            this.init()
          } 
        })
        .catch((err) => {
          console.log(err)
        })
    },
    makeSure() {
      let formData = new FormData();
      let data = this.monacoEditor.getValue()
      formData.append('content', data);
      
      this.$post('/config/api/resource', formData)
        .then((res) => {
          if (res.code == 10001) {
            this.handleClose()
            this.getResourceList()
            console.log(res)
          } else {
            
          }
        })
        .catch((err) => {
          console.log(err)
        })
    },
    //删除
    deleteRow(row) {
      this.$delete('/config/api/resource', {
        resourceId: row.id
      })
        .then((res) => {
          if (res.code == 10001) {
            this.$message({
              type: 'success',
              message: '删除成功！',
            })
            this.getResourceList()
            console.log(res)
          } else {
            
          }
        })
        .catch((err) => {
          console.log(err)
        })
    },
    //新增
    handleAdd() {
      this.dialogVisible = true
      this.edit = false
      this.$nextTick(() =>[
        this.initMoacoEditor('yaml', '')
      ])
    }
  },
  destroyed(){
    // this.monacoEditored.dispose();
  }
}
</script>


<style scoped lang="less">
.custom-panel{
  margin-top: 20px;
}
.dltbtn{
  color: red;
}
.custom-tools__info{
  color: rgba(16, 16, 16, 100);
  font-size: 18px;
  text-align: left;
  margin-top: 10px;
}
.custom-tools__content{
  background-color: #fff;
  margin-top: 10px;
  padding: 10px 20px;
}
.table-head{
  display: flex;
  margin-top: 10px;
  justify-content: space-between;
}
.dialog_main {
    display: flex;
    flex-wrap: wrap;

    .dialog_item {
        width: 100%;
        display: flex;
        align-items: center;
        margin-bottom: 10px;
    }

    .item_label {
        min-width: 60px;
    }
}
</style>
